name: Selenium UI Tests with Allure Report

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [Chrome, Firefox]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      ASPNETCORE_ENVIRONMENT: ci
      SauceDemo__LoginUsernameStandardUser: ${{ secrets.SAUCEDEMO_USERNAME_STANDARD }}
      SauceDemo__LoginUsernameLockedOutUser: ${{ secrets.SAUCEDEMO_USERNAME_LOCKEDOUT }}
      SauceDemo__LoginUsernameVisualUser: ${{ secrets.SAUCEDEMO_USERNAME_VISUAL }}
      SauceDemo__LoginPassword: ${{ secrets.SAUCEDEMO_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache WebDriverManager drivers
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: ${{ runner.os }}-wdm-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-wdm-

      - name: Restore dependencies
        run: dotnet restore ./SeleniumTraining.sln --locked-mode

      - name: Build project
        run: dotnet build ./SeleniumTraining.sln --configuration Release --no-restore

      - name: Run Selenium tests for ${{ matrix.browser }}
        env:
          TARGET_BROWSER_CI: ${{ matrix.browser }}
        run: |
          echo "Running tests for browser: ${{ matrix.browser }} with TARGET_BROWSER_CI=$TARGET_BROWSER_CI"
          dotnet test ./SeleniumTraining/SeleniumTraining.csproj \
            --configuration Release \
            --no-build \
            --logger "nunit;LogFilePath=allure-results/nunit-log-${{ matrix.browser }}.xml" \
            --filter "TestCategory=UI"

      - name: 'Debug: List All Possible Allure Results Locations'
        if: always()
        run: |
          echo "=== Searching for Allure results in common locations ==="
          echo "1. Project bin directory (expected location for Allure .NET output):"
          find ${{ github.workspace }}/SeleniumTraining/bin -name "allure-results" -type d -exec echo "Found allure-results in: {}" \; -exec ls -la {} \; 2>/dev/null || echo "No allure-results directory found in project bin path."
          
          echo "2. Searching for any JSON files that might be Allure results in project output:"
          find ${{ github.workspace }}/SeleniumTraining/bin -name "*-result.json" -o -name "*-container.json" 2>/dev/null | head -10 || echo "No Allure JSON files found in project bin path."
          
          echo "3. Current working directory contents:"
          pwd && ls -la

      - name: Copy Allure results to upload location
        if: always()
        run: |
          mkdir -p ${{ github.workspace }}/allure-upload
          FOUND_RESULTS=false
          
          find ${{ github.workspace }}/SeleniumTraining/bin -name "allure-results" -type d 2>/dev/null | while read dir; do
            if [ -n "$(ls -A "$dir" 2>/dev/null)" ]; then
              echo "Found results in: $dir and copying to ${{ github.workspace }}/allure-upload/"
              cp -r "$dir"/* ${{ github.workspace }}/allure-upload/
              FOUND_RESULTS=true
            else
              echo "Directory $dir is empty."
            fi
          done
          
          if [ "$FOUND_RESULTS" = false ] || [ -z "$(ls -A ${{ github.workspace }}/allure-upload 2>/dev/null)" ]; then
            echo "No Allure results found in expected locations - creating debug info"
            echo "Browser: ${{ matrix.browser }}" > ${{ github.workspace }}/allure-upload/debug-info-${{ matrix.browser }}.txt
            echo "Test run completed but no Allure JSON or NUnit XML files were copied for upload." >> ${{ github.workspace }}/allure-upload/debug-info-${{ matrix.browser }}.txt
            echo "Check if Allure.NUnit package is correctly generating files into project_output/allure-results/" >> ${{ github.workspace }}/allure-upload/debug-info-${{ matrix.browser }}.txt
            echo "And if NUnit logger is writing to project_output/allure-results/nunit-log-browser.xml" >> ${{ github.workspace }}/allure-upload/debug-info-${{ matrix.browser }}.txt
          fi
          
          echo "Final upload directory contents for browser ${{ matrix.browser }}:"
          ls -laR ${{ github.workspace }}/allure-upload/

      - name: Upload Allure test results for ${{ matrix.browser }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: ${{ github.workspace }}/allure-upload
          if-no-files-found: warn
          retention-days: 7

  generate-allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Download all Allure results artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./allure-results-downloaded

      - name: 'Debug: List downloaded artifacts structure'
        run: |
          ls -R ./allure-results-downloaded || echo "No artifacts downloaded or directory empty."
          find ./allure-results-downloaded -name "allure-results-*" -type d || echo "No allure-results-* directories found in download."

      - name: Aggregate Allure results
        run: |
          mkdir -p allure-results-final
          find ./allure-results-downloaded -maxdepth 1 -type d -name "allure-results-*" -print0 | while IFS= read -r -d $'\0' artifact_dir; do
            if [ -n "$(ls -A "$artifact_dir" 2>/dev/null)" ]; then
              rsync -av "$artifact_dir/" allure-results-final/
            else
              echo "Artifact directory $artifact_dir is empty."
            fi
          done

          ls -laR allure-results-final/
          if [ -z "$(ls -A allure-results-final)" ]; then
            echo "WARNING: No allure results found after aggregation! Report will be empty or based on dummy data."
            echo '{"uuid":"dummy-uuid","testCaseId":"dummy-testCaseId","fullName":"Dummy Test","labels":[{"name":"suite","value":"Dummy Suite"}],"status":"passed","start":1609459200000,"stop":1609459201000}' > allure-results-final/dummy-result.json
            echo "environment.properties" > allure-results-final/environment.properties
          fi

      - name: Allure Report Generation
        uses: simple-elf/allure-report-action@v1.7
        id: allure_report_generation
        with:
          allure_results: allure-results-final
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload Allure HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-html
          path: allure-report
          retention-days: 30

  deploy-allure-report-to-gh-pages:
    name: Deploy Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: generate-allure-report
    if: success() && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ github.server_url }}/${{ github.repository }}/
    permissions:
      contents: write
      pages: write
    steps:
      - name: Download Allure HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report-html
          path: ./report-to-deploy

      - name: 'Debug: List downloaded report structure for deployment'
        run: |
          ls -R ./report-to-deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-to-deploy
